stages:
  complete-covid_patients:
    cmd: dz run-step covid_patients complete
    deps:
    - src/covid_patients.py
    params:
    - zimmer.yaml:
      - aswan_projects.hun-covid.current_leaf
    outs:
    - data/dabble/covid_patients/complete
  complete-scimagojr:
    cmd: dz run-step scimagojr complete
    deps:
    - src/scimagojr.py
    outs:
    - data/dabble/scimagojr/complete
