stages:
  complete-covid_patients:
    cmd: dz run-step complete-covid_patients
    deps:
    - src/covid_patients.py
    params:
    - zimmer.yaml:
      - cron_bumps.complete-covid_patients
    outs:
    - data/dabble/covid_patients/complete:
        persist: true
  complete-scimagojr:
    cmd: dz run-step complete-scimagojr
    deps:
    - src/scimagojr.py
    outs:
    - data/dabble/scimagojr/complete:
        persist: true
