name: Scheduled Run
on:
  schedule:
  - cron: 0 16 * * *
jobs:
  cron-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python -m pip install --upgrade pip; pip install -r requirements.txt
    - name: Setup Git
      run: git config --global init.defaultBranch main;git config --global user.email
        "leo@dumbartonserum.com";git config --global user.name "Leo Dumbarton";git
        pull --tags
    - name: Bump crons
      env:
        CRON_TRIGGER: ${{ github.event.schedule }}
        ZIMMER_AUTH_HEX: ${{ secrets.ZIMMER_AUTH_HEX }}
        ZIMMER_PHRASE: ${{ secrets.ZIMMER_PHRASE }}
        GIT_HTTPS_TOKEN: ${{ secrets.GIT_HTTPS_TOKEN }}
      run: dz build-meta && dz update && dz run-cronjobs && dz publish-data
