name: Scheduled Run
on:
  schedule:
  - cron: 0 16 * * *
jobs:
  cron_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: python -m pip install --upgrade pip; pip install -r requirements.txt
    - name: Setup Git
      run: git config --global init.defaultBranch main;git config --global user.email
        "leo@dumbartonserum.com";git config --global user.name "Leo Dumbarton";git
        pull --tags
    - name: Bump crons
      env:
        CRON_TRIGGER: ${{ github.event.schedule }}
        ZIMMER_FULL_AUTH: ${{ secrets.ZIMMER_FULL_AUTH }}
        GIT_HTTPS_TOKEN: ${{ secrets.GIT_HTTPS_TOKEN }}
      run: datazimmer build-meta && dvc pull && datazimmer run-cronjobs && datazimmer
        publish-data
